### ISSUE TITLE
写入文件出错

### ISSUE THREAD

**Issue by tsai-xy** [longchengguxiao/nonebot_plugin_pvz#1]
![H2@OZDT R}$CI(DDX@Z{BBY](https://user-images.githubusercontent.com/118656253/213986253-ceea7eaf-068f-47d6-aed9-11263e2f6a79.png)
控制台啥都没有，使用bot小派蒙

**Comment by longchengguxiao** [comment]
> ![H2@OZDT R}$CI(DDX@Z{BBY](https://user-images.githubusercontent.com/118656253/213986253-ceea7eaf-068f-47d6-aed9-11263e2f6a79.png)
> 控制台啥都没有，使用bot小派蒙

应该是相对地址的问题，我稍等重新编写一下，修改完成后再回复告诉你一下

**Comment by longchengguxiao** [comment]
> ![H2@OZDT R}$CI(DDX@Z{BBY](https://user-images.githubusercontent.com/118656253/213986253-ceea7eaf-068f-47d6-aed9-11263e2f6a79.png)
> 控制台啥都没有，使用bot小派蒙

方便提供一个其他的联系方式吗，有些问题也想请教一下你:P

**Comment by tsai-xy** [comment]
我啥都不会

**Comment by longchengguxiao** [comment]
> 我啥都不会
好吧，那咱们nonebot的QQ交流群方便发我一下吗，我前一段时间有点事没有看群被移除群聊了，可以麻烦你再发我一次吗

**Comment by tsai-xy** [comment]
我也不知道，我用的nb2发行版的小派蒙，不是原版nb2

**Comment by longchengguxiao** [comment]
> 我也不知道，我用的nb2发行版的小派蒙，不是原版nb2

好的，那我明白了，主要是我这边不太方便测试，机器人被风控了。那我改好了再联系你吧

**Comment by longchengguxiao** [comment]
> ![H2@OZDT R}$CI(DDX@Z{BBY](https://user-images.githubusercontent.com/118656253/213986253-ceea7eaf-068f-47d6-aed9-11263e2f6a79.png)
> 控制台啥都没有，使用bot小派蒙

改了很多，可以重新尝试一下，如果更新插件失败，可以在虚拟环境中找到nonebot_plugin_pvz及其info文件进行删除操作，然后重新安装，最新版本为1.1.1。（命令 pip install --upgrade nonebot_plugin_pvz）
测试时建议先使用命令“查看背包”来进行插件注册，再使用“查看草坪”来开启草坪，然后测试签到，购买，商店等功能。
更新之后需要在bot.py中提前配置好定时器（具体请看readme.md），不过你用别人的bot应该配置的有。
总之即使你什么也不会，也希望可以留下一个联系方式，毕竟我这边不能进行测试，希望可以一起测试一下。我的邮箱是1298919732@qq.com，可以将你的联系方式私发在我的邮箱，如果可以的话那就太感谢了！

**Comment by longchengguxiao** [comment]
经过逐步测试，所有已知问题均解决，在测试版本下所有功能可以正常使用，请下载最新版本的安装包(v1.1.3)来获取，有问题及时交流解决，谢谢
