### ISSUE TITLE
新版本更迭的nonebot.param引入

### ISSUE THREAD

**Issue by longchengguxiao** [longchengguxiao/nonebot_plugin_pvz#2]
逐步引入，计划于XDU_script插件完善后更改

**Comment by tsai-xy** [comment]
![PP8WB 9`NU@UYK2~1B`7H%M](https://user-images.githubusercontent.com/118656253/214304244-1a54cb2c-5d95-48b6-9b7b-24b71b48c9ca.png)
还是有点问题

**Comment by longchengguxiao** [comment]
> ![PP8WB 9NU@UYK2~1B7H%M](https://user-images.githubusercontent.com/118656253/214304244-1a54cb2c-5d95-48b6-9b7b-24b71b48c9ca.png) 还是有点问题

你的版本是什么，更新了吗

**Comment by tsai-xy** [comment]
我刚装的

**Comment by tsai-xy** [comment]
![image](https://user-images.githubusercontent.com/118656253/214305379-9defbd0d-500b-410b-952a-5ddcc049b88e.png)

**Comment by longchengguxiao** [comment]
> 我刚装的

1.1.2你删掉，重装1.1.3

**Comment by longchengguxiao** [comment]
![image](https://user-images.githubusercontent.com/75836227/214305606-87d541ff-8269-4c2e-a2b6-4fb3691892ac.png)

**Comment by longchengguxiao** [comment]
![image](https://user-images.githubusercontent.com/75836227/214305776-28ac1334-6008-4eb9-a01d-77ed2307e5c5.png)
在这里我加了这行代码应该已经可以解决问题了

**Comment by tsai-xy** [comment]
我用的nb脚手架  poetry run nb plugin install nonebot-plugin-pvz  装上是1.1.2

**Comment by tsai-xy** [comment]
pip装也是
![image](https://user-images.githubusercontent.com/118656253/214307754-6960285f-6151-49fb-918e-e2f0b9fe0cbc.png)

**Comment by longchengguxiao** [comment]
> pip装也是
> ![image](https://user-images.githubusercontent.com/118656253/214307754-6960285f-6151-49fb-918e-e2f0b9fe0cbc.png)
> 

啊这，我也是用pip，你试试我刚刚发的命令，用--upgrade参数试试

**Comment by longchengguxiao** [comment]
> pip装也是
> ![image](https://user-images.githubusercontent.com/118656253/214307754-6960285f-6151-49fb-918e-e2f0b9fe0cbc.png)
> 

我又重新上传了一下，麻烦你重试一次

**Comment by longchengguxiao** [comment]
> pip装也是 ![image](https://user-images.githubusercontent.com/118656253/214307754-6960285f-6151-49fb-918e-e2f0b9fe0cbc.png)
![image](https://user-images.githubusercontent.com/75836227/214309528-f0848cd0-c901-4ff1-93cf-f1d752f0422e.png)

**Comment by tsai-xy** [comment]
行，默认源

**Comment by longchengguxiao** [comment]
> 行，默认源

好的，那你再试试，如果还有问题就再联系我

**Comment by tsai-xy** [comment]
poetry 虚拟环境下好像不会自动生成output文件夹 得自己建个文件夹，不然商店不可用。
![image](https://user-images.githubusercontent.com/118656253/214318017-5f0b2a27-6411-4a38-8d06-c6fd070be9d2.png)

**Comment by longchengguxiao** [comment]
> poetry 虚拟环境下好像不会自动生成output文件夹 得自己建个文件夹，不然商店不可用。
> ![image](https://user-images.githubusercontent.com/118656253/214318017-5f0b2a27-6411-4a38-8d06-c6fd070be9d2.png)
> 

我用了os.path.exist来查看是否存在文件夹，不存在就建立，你能看到是第几行报错吗，或者截一下完整的日志看看

**Comment by longchengguxiao** [comment]
> poetry 虚拟环境下好像不会自动生成output文件夹 得自己建个文件夹，不然商店不可用。
> ![image](https://user-images.githubusercontent.com/118656253/214318017-5f0b2a27-6411-4a38-8d06-c6fd070be9d2.png)
> 

好像是漏掉了，我修改一下，不知道什么原因，修改了这个地方的文件被没有修改的覆盖掉了

**Comment by tsai-xy** [comment]
01-24 22:05:51 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_pvz) failed.
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\LittlePaimon\bot.py", line 37, in <module>
    nonebot.run(app="__mp_main__:app", access_log=False)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-cfQJiKFR-py3.10\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-cfQJiKFR-py3.10\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-cfQJiKFR-py3.10\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-cfQJiKFR-py3.10\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1899, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-cfQJiKFR-py3.10\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-cfQJiKFR-py3.10\lib\site-packages\nonebot\message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-cfQJiKFR-py3.10\lib\site-packages\nonebot\internal\matcher\matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-cfQJiKFR-py3.10\lib\site-packages\nonebot\internal\matcher\matcher.py", line 702, in simple_run
    await handler(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-cfQJiKFR-py3.10\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-cfQJiKFR-py3.10\lib\site-packages\nonebot_plugin_pvz\__init__.py", line 1234, in _
    draw_test(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-cfQJiKFR-py3.10\lib\site-packages\nonebot_plugin_pvz\__init__.py", line 704, in draw_test
    img.save(save_path)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-cfQJiKFR-py3.10\lib\site-packages\PIL\Image.py", line 2428, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Administrator\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\littlepaimon-cfQJiKFR-py3.10\\lib\\site-packages\\nonebot_plugin_pvz\\images\\pvz\\output\\zombie_store.png'

**Comment by longchengguxiao** [comment]
> 01-24 22:05:51 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_pvz) failed. Traceback (most recent call last): File "C:\Users\Administrator\Desktop\LittlePaimon\bot.py", line 37, in nonebot.run(app="**mp_main**:app", access_log=False) File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-cfQJiKFR-py3.10\lib\site-packages\nonebot__init__.py", line 273, in run get_driver().run(*args, **kwargs) File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-cfQJiKFR-py3.10\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run uvicorn.run( File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-cfQJiKFR-py3.10\lib\site-packages\uvicorn\main.py", line 569, in run server.run() File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-cfQJiKFR-py3.10\lib\site-packages\uvicorn\server.py", line 60, in run return asyncio.run(self.serve(sockets=sockets)) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete self.run_forever() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever super().run_forever() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever self._run_once() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1899, in _run_once handle._run() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run self._context.run(self._callback, *self._args) File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-cfQJiKFR-py3.10\lib\site-packages\nonebot\message.py", line 142, in _check_matcher await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> 
> > File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-cfQJiKFR-py3.10\lib\site-packages\nonebot\message.py", line 188, in _run_matcher
> > await matcher.run(bot, event, state, stack, dependency_cache)
> > File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-cfQJiKFR-py3.10\lib\site-packages\nonebot\internal\matcher\matcher.py", line 727, in run
> > await self.simple_run(bot, event, state, stack, dependency_cache)
> > File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-cfQJiKFR-py3.10\lib\site-packages\nonebot\internal\matcher\matcher.py", line 702, in simple_run
> > await handler(
> > File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-cfQJiKFR-py3.10\lib\site-packages\nonebot\dependencies__init__.py", line 108, in **call**
> > return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> > File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-cfQJiKFR-py3.10\lib\site-packages\nonebot_plugin_pvz__init__.py", line 1234, in _
> > draw_test(
> > File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-cfQJiKFR-py3.10\lib\site-packages\nonebot_plugin_pvz__init__.py", line 704, in draw_test
> > img.save(save_path)
> > File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-cfQJiKFR-py3.10\lib\site-packages\PIL\Image.py", line 2428, in save
> > fp = builtins.open(filename, "w+b")
> > FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-cfQJiKFR-py3.10\lib\site-packages\nonebot_plugin_pvz\images\pvz\output\zombie_store.png'

已修改，麻烦更新1.14版本再次尝试，已经修复这个问题了

**Comment by tsai-xy** [comment]
![image](https://user-images.githubusercontent.com/118656253/214323973-0616673f-b966-448d-9d5a-10dda10ee336.png)
植物人机训练报错，僵尸可以。

**Comment by longchengguxiao** [comment]
> ![image](https://user-images.githubusercontent.com/118656253/214323973-0616673f-b966-448d-9d5a-10dda10ee336.png) 植物人机训练报错，僵尸可以。

麻烦再试一次，同版本下我这边没有报错，无法复现

**Comment by longchengguxiao** [comment]
![image](https://user-images.githubusercontent.com/75836227/214325602-d9dd5350-8f0b-4742-a2d5-bda6df8d8d1e.png)

**Comment by longchengguxiao** [comment]
> ![image](https://user-images.githubusercontent.com/118656253/214323973-0616673f-b966-448d-9d5a-10dda10ee336.png) 植物人机训练报错，僵尸可以。

错误已经发现，没有判断草坪是否为空导致，先已经修复，稍后上传，草坪不为空时验证无误

**Comment by tsai-xy** [comment]
是我没放植物

**Comment by tsai-xy** [comment]
可以加个反馈

**Comment by tsai-xy** [comment]
![image](https://user-images.githubusercontent.com/118656253/214333495-01417422-b891-4126-a7cd-d72ec69411d9.png)
植物人机训练 地狱   我先睡了， 加个q吧1726439534
