### ISSUE TITLE
背包的植物1个可以放很多次这个正常吗

### ISSUE THREAD

**Issue by Kiana1314** [longchengguxiao/nonebot_plugin_pvz#3]
![Screenshot_2023-01-26-02-38-54-335-edit_com tencent mobileqq](https://user-images.githubusercontent.com/107671434/214653146-845ec2dd-4b33-45fe-9431-7ead951ce928.jpg)

**Comment by longchengguxiao** [comment]
这个我稍后改一下，应该是查找的地方出错了

**Comment by longchengguxiao** [comment]
已经发布新版1.1.9，不过我现在在路上，没办法进行测试，新版本更改了一些语法适应nonebot rc3，修复了包括这个问题在内一些漏洞，请更新后尝试（github未上传更新）

**Comment by longchengguxiao** [comment]
已发布新版v2.0.0，经测试已修改此漏洞。另更新了上传以及下载数据功能，具体命令请看README.md，此问题关闭
