### ISSUE TITLE
背包植物无法放置

### ISSUE THREAD

**Issue by Kiana1314** [longchengguxiao/nonebot_plugin_pvz#5]
![image](https://user-images.githubusercontent.com/107671434/215240872-68dae6c1-adc8-49c6-950d-bc96535db657.png)

**Comment by longchengguxiao** [comment]
> ![image](https://user-images.githubusercontent.com/107671434/215240872-68dae6c1-adc8-49c6-950d-bc96535db657.png)

已经找到问题，请在最新的v1.2.2版本中进行查看，更新前别忘记下载数据以免造成丢失
![B48D109B51A5C634E488A60E73E539B5](https://user-images.githubusercontent.com/75836227/215241632-5ac741c5-38fb-4555-a01e-36f2b8cfffed.jpg)

**Comment by longchengguxiao** [comment]
> ![image](https://user-images.githubusercontent.com/107671434/215240872-68dae6c1-adc8-49c6-950d-bc96535db657.png)

另诚邀您加入群聊(719392400)来一同探讨插件未来的发展，不胜感激
